### ISSUE TITLE
2018-05-01 Meeting overall checklist

### ISSUE THREAD

**Issue by nathanhruby** [TucsonPython/meetings#1]
## Items to do in advance of the meeting
- [x] Ensure we have a topic and presenter (Name, Bio, GitHub username, Talk title & description)
- [x] Ensure we have a space and sponsor
- [x] Ensure we know what the projector setup is and what kind of connector it is
- [x] Update description on meetup
- [x] Confirm with Food/Beverage sponsor and get contact info 
- [x] Ensure presenter has correct info for leading Thank You slide and projector setup
- [x] Ensure someone will be early to met space sponsor, help setup, meet people

## Day of meetup
- [x] Touch base with presenter and ensure we are go-flight
- [x] Touch base with space sponsor and ensure we are go-flight
- [x] Touch base with food sponsor and ensure we are go-flight
- [x] Send reminder/update via meetup day of meeting about location, time, parking, etc..
- [x] Get there
- [x] DO IT

## Meeting Agenda
- Intro
- Thank You
- Sponsor Chat
- Announcements
- Next Meeting 
- Introduce speaker
- Present
- Q/A
- Wrap up, remind for next
